### ISSUE TITLE
`while` and `until` examples could be improved

### ISSUE THREAD

**Issue by MightyPork** [ash/raku-course#2]
I think a better example is needed - https://course.raku.org/essentials/loops/while/

The last message printed by the loop is always a lie

```
Enter a number: 20
You entered 20, which is not bigger than 10.
```

One fix could be

```raku
my $x = 0;
while $x <= 10 {
    $x = prompt 'Enter a number: ';
    say "You entered $x, which is not bigger than 10." if $x <= 10;
}
say "$x is bigger than 10.";
```
though, I don't like duplicating the condition. Maybe just removing "which is not bigger than 10" would suffice.

**Comment by ash** [comment]
Good catch, thank you.

54c12c4
