### ISSUE TITLE
Exercise `number-in-limits` uses ternary that was not covered yet

### ISSUE THREAD

**Issue by MightyPork** [ash/raku-course#3]
This example (https://course.raku.org/essentials/ranges/exercises/number-in-limits/) can be solved using the ternary operator - that is the official solution - or using `if`, but none of these were covered by the time you get to the exercise when doing the course sequentially.

Maybe there should be a hint to look at the ternary syntax ahead of time, or change the exercise somehow.

**Comment by ash** [comment]
The code should be updated.

**Comment by ash** [comment]
@MightyPork, thanks a lot once again. deb21dd
