### ISSUE TITLE
Quiz "declaring more variables" broken in Firefox

### ISSUE THREAD

**Issue by MightyPork** [ash/raku-course#4]
You can't see what's in the fields. It's OK in Chrome-based browsers.

this is Firefox 84 on Linux with KDE Plasma desktop, Breeze theme (default).

![Screenshot_20210117_144250](https://user-images.githubusercontent.com/2041118/104844787-7a1c8d00-58d2-11eb-8b95-65f8fc7afe8e.png)

![Screenshot_20210117_144312](https://user-images.githubusercontent.com/2041118/104844792-7d177d80-58d2-11eb-99ab-fb76cbf3bbf1.png)

It looks okay when I set the width to 1.6em or more. This may depend on the font used.
Or set the `<input>` elements' border using CSS, that stops Firefox from using the default style.

```
border-radius: 3px;
border: 1px solid gray;
text-align: center;
```

there's gonna be the same problem in other similar quizes as well... like here:

![Screenshot_20210117_145505](https://user-images.githubusercontent.com/2041118/104845107-054a5280-58d4-11eb-96f7-86385ad5519d.png)

**Comment by ash** [comment]
Not sure how to reproduce it. It works correctly in FF 84.0.2 on a Mac.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/25134/104846153-69234a00-58d9-11eb-9bdd-f150efad6a4b.png">

**Comment by MightyPork** [comment]
I think the form styles the browser uses by default are taken from the OS. One possibility is using a Kubuntu VM. Or just set the smallest quiz field size to 1.6em or 2em and hope it will be okay

**Comment by MightyPork** [comment]
It can be reproduced using VirtualBox with this image: https://www.linuxvmimages.com/images/kubuntu-2004/

Firefox is pre-installed

![Screenshot_20210117_155658](https://user-images.githubusercontent.com/2041118/104846829-cd93d880-58dc-11eb-93f6-2faec62c7fa2.png)

**Comment by ash** [comment]
Looks fine now. Can you please check? 

<img width="268" alt="image" src="https://user-images.githubusercontent.com/25134/104847984-35e5b880-58e3-11eb-8bf0-062e461e348a.png">

**Comment by MightyPork** [comment]
Yup looks fine here too
