### ISSUE TITLE
`if` quiz does not accept unicode ≥

### ISSUE THREAD

**Issue by MightyPork** [ash/raku-course#5]
Another small bug ;)

![Screenshot_20210117_165447](https://user-images.githubusercontent.com/2041118/104848353-de484c80-58e4-11eb-97bc-1a9f536fd40c.png)

I would fix it myself in a PR, but I'm not sure how to specify multiple correct answers in the quiz format.

**Comment by ash** [comment]
Lol, I thought I have no such cases with more than one correct answer. Requires chaining JS logic in _include/quiz.html. Will do later.

**Comment by ash** [comment]
0bf4235

<img width="622" alt="image" src="https://user-images.githubusercontent.com/25134/104848950-865f1500-58e7-11eb-95a3-29947ff364bb.png">
