### ISSUE TITLE
Arrays/lists section misleading

### ISSUE THREAD

**Issue by MightyPork** [ash/raku-course#9]
I think [this section](https://course.raku.org/essentials/positionals/quoting-string-arrays/) should clarify that what the angle bracket syntax creates is a List, not Array. Lists are covered later in the section.

```
> <zero one two three four five six seven eight nine>
(zero one two three four five six seven eight nine)
```

Actually, now revisiting the Arrays topic, `'Paris', 'Rome', 'Berlin'` and `('Paris', 'Rome', 'Berlin')` also create a list, not array.

Maybe list should be taught before array?

`<...>` is taught as creating array of strings, but then you get [this quiz](https://course.raku.org/essentials/positionals/lists/quiz1/) wrong because they are lists...

If I understand it right, it only becomes an array after being assigned to the `@` sigil variable, similar to how IntStr can become Int

```
> @asArray = <zero one two three four five six seven eight nine>
[zero one two three four five six seven eight nine]
```
Though, at this point I'm genuinely puzzled by sigils, especially since you then have [this quiz 2*](https://course.raku.org/essentials/positionals/lists/quiz2/) which just doesn't make sense with what was taught so far. A teaster?

**Comment by MightyPork** [comment]
This article is very revealing, I now kind of understand sigils and also have discovered the binding operator.

https://perl6advent.wordpress.com/2017/12/02/perl-6-sigils-variables-and-containers/

```
> my $what1 := 1,2,3
(1 2 3)
> my $what2 = 1,2,3
(1 2 3)
> my @what3 := 1,2,3
(1 2 3)
> my @what4 = 1,2,3 # list to array magic happening
[1 2 3]
> 
```

**Comment by ash** [comment]
6f18bc2

**Comment by MightyPork** [comment]
It's much better!

One issue, `positionals/lists/quiz1` asks about the `<a b c>` syntax, but that is first covered in the following section (`positionals/quoting-string-arrays`)

and a typo in `positionals/subscripting-ranges`, "assess" instead of "access"

**Comment by ash** [comment]
Thanks. 526cf50 and 46e2175
